/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.components;

import javax.swing.JOptionPane;

/**
 *
 * @author Mangal Tamang
 */
public class CalculatorExample extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorExample
     */
    public CalculatorExample() {
        initComponents();
    }
    
    // custom operation method here
    public double doAddition(double number_one, double number_two){
        return number_one + number_two;
    }
    
    public double doSubtraction(double number_one, double number_two){
        return number_one - number_two;
    }
    
    public double doMultiplication(double number_one, double number_two){
        return number_one * number_two;
    }
    
    public double doDivision(double number_one, double number_two){
        double result = 0.00;
        if(number_two == 0){
            JOptionPane.showMessageDialog(rootPane, "Number two must be greater than zero");
        } else {
            result = number_one/number_two;
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title = new javax.swing.JLabel();
        label_number_one = new javax.swing.JLabel();
        text_number_one = new javax.swing.JTextField();
        label_number_two = new javax.swing.JLabel();
        text_number_two = new javax.swing.JTextField();
        label_operation = new javax.swing.JLabel();
        cmb_operation = new javax.swing.JComboBox<>();
        label_output = new javax.swing.JLabel();
        text_output = new javax.swing.JTextField();
        button_show = new javax.swing.JButton();
        button_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_title.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("CALCULATOR BASIC");

        label_number_one.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_number_one.setText("Number One:");

        text_number_one.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        label_number_two.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_number_two.setText("Number Two:");

        text_number_two.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        label_operation.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_operation.setText("Select Operation:");

        cmb_operation.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cmb_operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADD", "SUBTRACT", "MULTIPLY", "DIVIDE" }));

        label_output.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label_output.setText("Output Here:");

        text_output.setEditable(false);
        text_output.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        text_output.setEnabled(false);

        button_show.setText("SHOW");
        button_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_showActionPerformed(evt);
            }
        });

        button_reset.setText("RESET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_number_one, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(text_number_one, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_number_two, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_operation, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(label_output, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_operation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_number_two, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(text_output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(button_show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_title)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_number_one, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_number_one, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_number_two, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_number_two, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_operation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_output, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_output, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_show, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_showActionPerformed
        // TODO add your handling code here:
        // parsing String value to double
        try {
            double number_one = 0.00;
            double number_two = 0.00;
            if (text_number_one.equals("")) {
                System.out.println("Please enter number one");
            } else {
                number_one = Double.parseDouble(text_number_one.getText());
            }
            if (text_number_two.equals("")) {
                System.out.println("Please enter number two");
            } else {
                number_two = Double.parseDouble(text_number_two.getText());
            }

            String operation = cmb_operation.getSelectedItem().toString();
            if (operation.equals("ADD")) {
                double result = this.doAddition(number_one, number_two);
                System.out.println("Result: " + result);
                text_output.setText(result + "");
                JOptionPane.showMessageDialog(rootPane, result);
            } else if (operation.equals("SUBTRACT")) {
                double result = this.doSubtraction(number_one, number_two);
                System.out.println("Result: " + result);
                text_output.setText(result + "");
                JOptionPane.showMessageDialog(rootPane, result);
            } else if (operation.equals("MULTIPLY")) {
                double result = this.doMultiplication(number_one, number_two);
                System.out.println("Result: " + result);
                text_output.setText(result + "");
                JOptionPane.showMessageDialog(rootPane, result);
            } else if (operation.equals("DIVIDE")) {
                double result = this.doDivision(number_one, number_two);
                System.out.println("Result: " + result);
                text_output.setText(result + "");
                JOptionPane.showMessageDialog(rootPane, result);
            }
        } catch (NumberFormatException ex) {
            System.out.println("Please enter valid number");
            // to show message to user
            JOptionPane.showMessageDialog(rootPane, "Please enter numeric value only.");
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_button_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_reset;
    private javax.swing.JButton button_show;
    private javax.swing.JComboBox<String> cmb_operation;
    private javax.swing.JLabel label_number_one;
    private javax.swing.JLabel label_number_two;
    private javax.swing.JLabel label_operation;
    private javax.swing.JLabel label_output;
    private javax.swing.JLabel label_title;
    private javax.swing.JTextField text_number_one;
    private javax.swing.JTextField text_number_two;
    private javax.swing.JTextField text_output;
    // End of variables declaration//GEN-END:variables
}
