package thirdsem.game.guessnumber;

import javax.swing.JOptionPane;
import java.util.Random;
import java.awt.Color;

/**
 *
 * @author Mangal Tamang
 */
public class GuessTheNumber extends javax.swing.JFrame {
    public int count = 0;
    
    /**
     * Creates new form GuessTheNumber
     */
    public GuessTheNumber() {
        initComponents();
        this.clearButtonColor();
    }
    
    /**
     * @return generated_number
     */
    public int generateNumber(){
        // Using Random package to generate number
        Random random = new Random();
        int generated_number = random.nextInt(1, 13);
        return generated_number;
    }
    
    /**
     * @param number
     * 
     */
    public void checkGuessedNumber(int number){
        int generated_number = this.generateNumber();
        if(number == generated_number){
            text_result.setText("Guess number is correct");
            setButtonColor(generated_number, Color.GREEN);
            JOptionPane.showMessageDialog(rootPane, "Match found after trying " + this.count + " times");
            text_number.setText("");
            this.clearButtonColor();
            this.count = 0;
            text_count.setText(this.count + "");
        } else {
            text_result.setText("Guess failed. The number is: " + generated_number);
            setButtonColor(generated_number, Color.RED);
            this.count++;
            text_count.setText(this.count + "");
        }
    }
    
    public void setButtonColor(int generated_number, Color color){
        switch (generated_number) {
            case 1:
                btn_one.setBackground(color);
                btn_one.setForeground(Color.WHITE);
                break;
            case 2:
                btn_two.setBackground(color);
                btn_two.setForeground(Color.white);
                break;
            case 3:
                btn_three.setBackground(color);
                btn_three.setForeground(Color.white);
                break;
            case 4:
                btn_four.setBackground(color);
                btn_four.setForeground(Color.white);
                break;
            case 5:
                btn_five.setBackground(color);
                btn_five.setForeground(Color.white);
                break;
            case 6:
                btn_six.setBackground(color);
                btn_six.setForeground(Color.white);
                break;
            case 7:
                btn_seven.setBackground(color);
                btn_seven.setForeground(Color.white);
                break;
            case 8:
                btn_eight.setBackground(color);
                btn_eight.setForeground(Color.white);
                break;
            case 9:
                btn_nine.setBackground(color);
                btn_nine.setForeground(Color.white);
                break;
            case 10:
                btn_ten.setBackground(color);
                btn_ten.setForeground(Color.white);
                break;
            case 11:
                btn_eleven.setBackground(color);
                btn_eleven.setForeground(Color.white);
                break;
            case 12:
                btn_twelve.setBackground(color);
                btn_twelve.setForeground(Color.white);
                break;
        }
    }
    
    public void clearButtonColor(){
        btn_one.setForeground(Color.WHITE);
        btn_one.setBackground(Color.DARK_GRAY);
        
        btn_two.setForeground(Color.WHITE);
        btn_two.setBackground(Color.DARK_GRAY);
        
        btn_three.setForeground(Color.WHITE);
        btn_three.setBackground(Color.DARK_GRAY);
        
        btn_four.setForeground(Color.WHITE);
        btn_four.setBackground(Color.DARK_GRAY);
        
        btn_five.setForeground(Color.WHITE);
        btn_five.setBackground(Color.DARK_GRAY);
        
        btn_six.setForeground(Color.WHITE);
        btn_six.setBackground(Color.DARK_GRAY);
        
        btn_seven.setForeground(Color.WHITE);
        btn_seven.setBackground(Color.DARK_GRAY);
        
        btn_eight.setForeground(Color.WHITE);
        btn_eight.setBackground(Color.DARK_GRAY);
        
        btn_nine.setForeground(Color.WHITE);
        btn_nine.setBackground(Color.DARK_GRAY);
        
        btn_ten.setForeground(Color.WHITE);
        btn_ten.setBackground(Color.DARK_GRAY);
        
        btn_eleven.setForeground(Color.WHITE);
        btn_eleven.setBackground(Color.DARK_GRAY);
        
        btn_twelve.setForeground(Color.WHITE);
        btn_twelve.setBackground(Color.DARK_GRAY);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_number = new javax.swing.JTextField();
        btn_guess = new javax.swing.JButton();
        btn_one = new javax.swing.JButton();
        btn_five = new javax.swing.JButton();
        btn_two = new javax.swing.JButton();
        btn_six = new javax.swing.JButton();
        btn_four = new javax.swing.JButton();
        btn_eight = new javax.swing.JButton();
        btn_three = new javax.swing.JButton();
        btn_seven = new javax.swing.JButton();
        btn_nine = new javax.swing.JButton();
        btn_ten = new javax.swing.JButton();
        btn_eleven = new javax.swing.JButton();
        btn_twelve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        text_result = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_count = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guess The Number");

        jLabel2.setText("Enter Number :");

        btn_guess.setText("GUESS");
        btn_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guessActionPerformed(evt);
            }
        });

        btn_one.setText("1");

        btn_five.setText("5");

        btn_two.setText("2");

        btn_six.setText("6");

        btn_four.setText("4");
        btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fourActionPerformed(evt);
            }
        });

        btn_eight.setText("8");

        btn_three.setText("3");

        btn_seven.setText("7");

        btn_nine.setText("9");

        btn_ten.setText("10");

        btn_eleven.setText("11");

        btn_twelve.setText("12");

        jLabel3.setText("Result :");

        text_result.setEditable(false);

        jLabel4.setText("Count:");

        text_count.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_guess, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(text_number)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(btn_nine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_five, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_one, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_eleven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_twelve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(text_result)
                            .addComponent(text_count))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_number, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btn_eleven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_twelve, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_result, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_count, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fourActionPerformed

    private void btn_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guessActionPerformed
        // TODO add your handling code here:
        String guess_number = text_number.getText();
        if(guess_number.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter number first");
        } else {
            try {
                int number = Integer.parseInt(guess_number);
                this.clearButtonColor();
                // checking the number
                this.checkGuessedNumber(number);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Must be numeric value");
            }
        }
    }//GEN-LAST:event_btn_guessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessTheNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessTheNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eight;
    private javax.swing.JButton btn_eleven;
    private javax.swing.JButton btn_five;
    private javax.swing.JButton btn_four;
    private javax.swing.JButton btn_guess;
    private javax.swing.JButton btn_nine;
    private javax.swing.JButton btn_one;
    private javax.swing.JButton btn_seven;
    private javax.swing.JButton btn_six;
    private javax.swing.JButton btn_ten;
    private javax.swing.JButton btn_three;
    private javax.swing.JButton btn_twelve;
    private javax.swing.JButton btn_two;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField text_count;
    private javax.swing.JTextField text_number;
    private javax.swing.JTextField text_result;
    // End of variables declaration//GEN-END:variables
}
